

//
// Autogenerated by gaxb ( https://github.com/SmallPlanet/gaxb )
//
using System.Collections.Generic;

public partial class LDGAllEquipment : LDGAllEquipmentBase {

	public static List<LDGEquipment> GetAllEquipment() {
		string equipmentXML = PlanetUnityResourceCache.GetTextFile("game/equipment");
		LDGAllEquipment all = LD30Game.loadXML (equipmentXML, null, null) as LDGAllEquipment;

		List<LDGEquipment> equipment = new List<LDGEquipment> ();
		foreach (object o in all.Equipments) {
			equipment.Add (o as LDGEquipment);
		}
		return equipment;
	}

}
