

//
// Autogenerated by gaxb ( https://github.com/SmallPlanet/gaxb )
//

using System;
using System.Xml;
using System.Text;
using System.Reflection;
using System.Collections.Generic;
using System.Collections;


public partial class LDGShip : LDGShipBase {
	
	public LDGShip()
	{
	}
	
	
	public LDGShip(
			int player,
			float structure,
			float armor,
			float shields ) : this()
	{
		this.player = player;
		this.playerExists = true;

		this.structure = structure;
		this.structureExists = true;

		this.armor = armor;
		this.armorExists = true;

		this.shields = shields;
		this.shieldsExists = true;
	}

	

}




public class LDGShipBase : ILD30Game {


	private static Type planetOverride = Type.GetType("PlanetUnityOverride");
	private static MethodInfo processStringMethod = planetOverride.GetMethod("processString", BindingFlags.Public | BindingFlags.Static);


	public object parent;
	public string xmlns;


	// XML Attributes
	public int player;
	public bool playerExists;

	public float structure;
	public bool structureExists;

	public float armor;
	public bool armorExists;

	public float shields;
	public bool shieldsExists;




	// XML Sequences
	public List<object> Equipments = new List<object>();
	

	
	public void SetPlayer(int v) { player = v; playerExists = true; } 
	public void SetStructure(float v) { structure = v; structureExists = true; } 
	public void SetArmor(float v) { armor = v; armorExists = true; } 
	public void SetShields(float v) { shields = v; shieldsExists = true; } 


	public virtual void gaxb_unload()
	{

	}
	
	public void gaxb_addToParent()
	{
		if(parent != null)
		{
			FieldInfo parentField = parent.GetType().GetField("Ship");
			List<object> parentChildren = null;
			
			if(parentField != null)
			{
				parentField.SetValue(parent, this);
				
				parentField = parent.GetType().GetField("ShipExists");
				parentField.SetValue(parent, true);
			}
			else
			{
				parentField = parent.GetType().GetField("Ships");
				
				if(parentField != null)
				{
					parentChildren = (List<object>)(parentField.GetValue(parent));
				}
				else
				{
					parentField = parent.GetType().GetField("LD30Games");
					if(parentField != null)
					{
						parentChildren = (List<object>)(parentField.GetValue(parent));
					}
				}
				if(parentChildren == null)
				{
					FieldInfo childrenField = parent.GetType().GetField("children");
					if(childrenField != null)
					{
						parentChildren = (List<object>)childrenField.GetValue(parent);
					}
				}
				if(parentChildren != null)
				{
					parentChildren.Add(this);
				}
				
			}
		}
	}

	public virtual void gaxb_load(XmlReader reader, object _parent, Hashtable args)
	{

		if(reader == null && _parent == null)
			return;
		
		parent = _parent;
		
		if(this.GetType() == typeof( LDGShip ))
		{
			gaxb_addToParent();
		}
		
		xmlns = reader.GetAttribute("xmlns");
		

		string attr;
		attr = reader.GetAttribute("player");
		if(attr != null && planetOverride != null) { attr = processStringMethod.Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr != null) { player = int.Parse(attr); playerExists = true; } 
		
		attr = reader.GetAttribute("structure");
		if(attr != null && planetOverride != null) { attr = processStringMethod.Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr != null) { structure = float.Parse(attr); structureExists = true; } 
		
		attr = reader.GetAttribute("armor");
		if(attr != null && planetOverride != null) { attr = processStringMethod.Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr != null) { armor = float.Parse(attr); armorExists = true; } 
		
		attr = reader.GetAttribute("shields");
		if(attr != null && planetOverride != null) { attr = processStringMethod.Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr != null) { shields = float.Parse(attr); shieldsExists = true; } 
		

	}
	
	
	
	
	
	
	
	public virtual void gaxb_appendXMLAttributes(StringBuilder sb)
	{

		if(playerExists) { sb.AppendFormat (" {0}=\"{1}\"", "player", player); }
		if(structureExists) { sb.AppendFormat (" {0}=\"{1}\"", "structure", structure.ToString ("0.##")); }
		if(armorExists) { sb.AppendFormat (" {0}=\"{1}\"", "armor", armor.ToString ("0.##")); }
		if(shieldsExists) { sb.AppendFormat (" {0}=\"{1}\"", "shields", shields.ToString ("0.##")); }

	}
	
	public virtual void gaxb_appendXMLSequences(StringBuilder sb)
	{

		MethodInfo mInfo;		foreach(object o in Equipments) { mInfo = o.GetType().GetMethod("gaxb_appendXML"); if(mInfo != null) { mInfo.Invoke (o, new[] { sb }); } else { sb.AppendFormat ("<{0}>{1}</{0}>", "Equipment", o); } }
	

	}
	
	public virtual void gaxb_appendXML(StringBuilder sb)
	{
		if(sb.Length == 0)
		{
			sb.AppendFormat ("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		}
		
		sb.AppendFormat ("<{0}", "Ship");
		
		if(xmlns != null)
		{
			sb.AppendFormat (" {0}=\"{1}\"", "xmlns", xmlns);
		}
		
		gaxb_appendXMLAttributes(sb);
		
		
		StringBuilder seq = new StringBuilder();
		seq.AppendFormat(" ");
		gaxb_appendXMLSequences(seq);
		
		if(seq.Length == 1)
		{
			sb.AppendFormat (" />");
		}
		else
		{
			sb.AppendFormat (">{0}</{1}>", seq.ToString(), "Ship");
		}
	}
}
